import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Header, Hero, VideoMain, ServicesCloud } from '../components'

{/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}


export default function Home() {
  return (
    <>
      <Head>
        <title>Clever IDEAS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <ServicesCloud />
      {/* <VideoMain /> */}
    </>
  )
}
